# Generated by Django 3.2 on 2021-08-19 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=12)),
                ('invoide_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quntity', models.IntegerField()),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('apple', 'apple'), ('orange', 'orange'), ('guava', 'guava'), ('mango', 'mango'), ('banana', 'banana')], default='', max_length=20)),
                ('quantity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project1.quantity')),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=20)),
                ('seller_addess', models.CharField(max_length=20)),
                ('seller_phone', models.CharField(max_length=12)),
                ('buyer_name', models.CharField(max_length=20)),
                ('buyer_address', models.CharField(max_length=20)),
                ('buyer_phone', models.CharField(max_length=12)),
                ('invoide_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project1.invoice')),
            ],
        ),
    ]
