# Generated by Django 3.2 on 2021-08-19 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0002_alter_quantity_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quantity',
            name='amount',
        ),
        migrations.AddField(
            model_name='product',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
