# Generated by Django 3.2 on 2021-08-19 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0004_auto_20210819_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='invoide_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project1.invoice'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_no',
            field=models.CharField(auto_created=True, blank=True, default='h', max_length=12),
        ),
    ]
