# Generated by Django 3.2 on 2021-08-19 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0005_auto_20210819_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=20)),
                ('invoice_date', models.DateTimeField(auto_now_add=True)),
                ('seller_name', models.CharField(max_length=30)),
                ('seller_address', models.CharField(max_length=30)),
                ('seller_phone', models.CharField(max_length=20)),
                ('buyer_name', models.CharField(max_length=20)),
                ('buyer_address', models.CharField(max_length=40)),
                ('buyer_phone', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Information',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.AddField(
            model_name='user_details',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project1.products'),
        ),
    ]
