# Generated by Django 3.2 on 2021-08-19 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0006_auto_20210819_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
