# Generated by Django 3.2 on 2021-08-19 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0008_auto_20210819_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='products',
        ),
        migrations.AddField(
            model_name='products',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='project1.user_details'),
        ),
    ]
