# Generated by Django 3.2 on 2021-08-19 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0009_auto_20210819_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project1.user_details'),
        ),
    ]
